"""empty message

Revision ID: 96daf3f980cb
Revises: f6d682b974ef
Create Date: 2022-12-06 12:18:43.106696

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '96daf3f980cb'
down_revision = 'f6d682b974ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendship',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id_self', sa.Integer(), nullable=False),
    sa.Column('user_id_friend', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id_friend'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id_self'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('friends')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id_self', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id_friend', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id_friend'], ['users.id'], name='friends_user_id_friend_fkey'),
    sa.ForeignKeyConstraint(['user_id_self'], ['users.id'], name='friends_user_id_self_fkey'),
    sa.PrimaryKeyConstraint('id', name='friends_pkey')
    )
    op.drop_table('friendship')
    # ### end Alembic commands ###
