"""empty message

Revision ID: f6d682b974ef
Revises: 723d2dedb3bf
Create Date: 2022-12-05 10:44:33.344277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6d682b974ef'
down_revision = '723d2dedb3bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id_self', sa.Integer(), nullable=False),
    sa.Column('user_id_friend', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id_friend'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id_self'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friends')
    # ### end Alembic commands ###
