"""empty message

Revision ID: f0312ea9958a
Revises: 96daf3f980cb
Create Date: 2022-12-15 15:35:01.322212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0312ea9958a'
down_revision = '96daf3f980cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server_members', sa.Column('member_since', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server_members', 'member_since')
    # ### end Alembic commands ###
