"""empty message

Revision ID: 723d2dedb3bf
Revises: 104f394f1134
Create Date: 2022-06-16 00:35:03.741300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '723d2dedb3bf'
down_revision = '104f394f1134'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('servers', 'public',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('users', sa.Column('online', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'online')
    op.alter_column('servers', 'public',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
