"""empty message

Revision ID: 2da108ed6444
Revises: a0c4d1d34b12
Create Date: 2023-02-13 12:24:14.849853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2da108ed6444'
down_revision = 'a0c4d1d34b12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendship_request',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('self_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['self_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('friendship', sa.Column('self_id', sa.Integer(), nullable=False))
    op.add_column('friendship', sa.Column('friend_id', sa.Integer(), nullable=False))
    op.drop_constraint('friendship_user_id_self_fkey', 'friendship', type_='foreignkey')
    op.drop_constraint('friendship_user_id_friend_fkey', 'friendship', type_='foreignkey')
    op.create_foreign_key(None, 'friendship', 'users', ['self_id'], ['id'])
    op.create_foreign_key(None, 'friendship', 'users', ['friend_id'], ['id'])
    op.drop_column('friendship', 'user_id_friend')
    op.drop_column('friendship', 'user_id_self')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friendship', sa.Column('user_id_self', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('friendship', sa.Column('user_id_friend', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'friendship', type_='foreignkey')
    op.drop_constraint(None, 'friendship', type_='foreignkey')
    op.create_foreign_key('friendship_user_id_friend_fkey', 'friendship', 'users', ['user_id_friend'], ['id'])
    op.create_foreign_key('friendship_user_id_self_fkey', 'friendship', 'users', ['user_id_self'], ['id'])
    op.drop_column('friendship', 'friend_id')
    op.drop_column('friendship', 'self_id')
    op.drop_table('friendship_request')
    # ### end Alembic commands ###
