"""empty message

Revision ID: 6107e75afe62
Revises: b046e024f7df
Create Date: 2023-03-08 13:31:23.556951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6107e75afe62'
down_revision = 'b046e024f7df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('direct_messages', sa.Column('server_invite', sa.Boolean(), nullable=True))
    op.add_column('direct_messages', sa.Column('server_invite_id', sa.Integer(), nullable=True))
    op.drop_column('direct_messages', 'serverInviteId')
    op.drop_column('direct_messages', 'serverInvite')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('direct_messages', sa.Column('serverInvite', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('direct_messages', sa.Column('serverInviteId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('direct_messages', 'server_invite_id')
    op.drop_column('direct_messages', 'server_invite')
    # ### end Alembic commands ###
