"""empty message

Revision ID: 9f71bc883fbb
Revises: 
Create Date: 2023-02-23 13:20:30.068914

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9f71bc883fbb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_friendships')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_friendships',
    sa.Column('friend_a_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('friend_b_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('friendship_start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['friend_a_id'], ['users.id'], name='user_friendships_friend_a_id_fkey'),
    sa.ForeignKeyConstraint(['friend_b_id'], ['users.id'], name='user_friendships_friend_b_id_fkey'),
    sa.PrimaryKeyConstraint('friend_a_id', 'friend_b_id', name='user_friendships_pkey')
    )
    # ### end Alembic commands ###
