"""empty message

Revision ID: b046e024f7df
Revises: 9f71bc883fbb
Create Date: 2023-03-07 12:09:19.065633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b046e024f7df'
down_revision = '9f71bc883fbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('direct_messages', sa.Column('serverInvite', sa.Boolean(), nullable=True))
    op.add_column('direct_messages', sa.Column('serverInviteId', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('direct_messages', 'serverInviteId')
    op.drop_column('direct_messages', 'serverInvite')
    # ### end Alembic commands ###
