"""empty message

Revision ID: f5ac982fe546
Revises: 2da108ed6444
Create Date: 2023-02-15 15:45:58.374752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5ac982fe546'
down_revision = '2da108ed6444'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friendship', sa.Column('dm_uuid', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('friendship', 'dm_uuid')
    # ### end Alembic commands ###
